[workspace]
members = ["sealevel-nostd-entrypoint", "example-program"]
resolver = "2"


[workspace.dependencies]
sealevel-nostd-entrypoint = { path = "./sealevel-nostd-entrypoint" }
solana-program = "2"
solana-program-test = "2"
solana-sdk = "2"
